#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /users
  controller: App\Controller\AuthController::register
  methods: POST

users:
  path: /users
  controller: App\Controller\AuthController::getUsers
  methods: GET

api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::getTokenUser

test:
  path: /api/test
  controller: App\Controller\ApiController::test

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }




